const semestersData = [
  { number: 1, name: 'Semester 1', branch: 'CSE' },
  { number: 2, name: 'Semester 2', branch: 'CSE' },
  { number: 3, name: 'Semester 3', branch: 'CSE' },
  { number: 4, name: 'Semester 4', branch: 'CSE' },
  { number: 5, name: 'Semester 5', branch: 'CSE' },
  { number: 6, name: 'Semester 6', branch: 'CSE' },
  { number: 7, name: 'Semester 7', branch: 'CSE' },
  { number: 8, name: 'Semester 8', branch: 'CSE' },
];

const subjectsData = [
  {
    name: 'Database Management Systems',
    code: 'CS501',
    semester: 5,
    branch: 'CSE',
    credits: 4,
    description:
      'Comprehensive study of database architecture, relational models, SQL, normalization, transaction processing, concurrency control, and indexing mechanisms.',
    units: [
      {
        unitNumber: 1,
        title: 'Introduction to DBMS & Relational Model',
        description: 'Database architecture, data models, ER diagrams, relational algebra, and tuple relational calculus.',
        topics: [
          'Database Architecture & 3-Schema Architecture',
          'ER Modeling & Extended ER',
          'Relational Algebra Operations',
          'Tuple Relational Calculus',
          'Domain Relational Calculus',
        ],
      },
      {
        unitNumber: 2,
        title: 'SQL & Database Integrity',
        description: 'Structured Query Language, DDL, DML, complex joins, views, triggers, and integrity constraints.',
        topics: [
          'DDL, DML, and DCL Commands',
          'Nested Subqueries & Correlated Queries',
          'Aggregate Functions & GROUP BY / HAVING',
          'Views, Assertions, and Triggers',
          'Integrity Constraints & Foreign Keys',
        ],
      },
      {
        unitNumber: 3,
        title: 'Relational Database Design & Normalization',
        description: 'Functional dependencies, normal forms (1NF to BCNF, 4NF), and lossless decomposition.',
        topics: [
          'Functional Dependencies & Armstrong Axioms',
          'Canonical Cover & Attribute Closure',
          '1NF, 2NF, 3NF, and BCNF',
          'Lossless Join Decomposition',
          'Dependency Preservation',
          'Multi-valued Dependencies & 4NF',
        ],
      },
      {
        unitNumber: 4,
        title: 'Transaction Management & Concurrency Control',
        description: 'ACID properties, serializability, lock-based protocols, two-phase locking, and deadlocks.',
        topics: [
          'ACID Properties of Transactions',
          'Conflict and View Serializability',
          'Two-Phase Locking (2PL & Strict 2PL)',
          'Timestamp Ordering Protocol',
          'Deadlock Detection, Prevention & Recovery',
        ],
      },
      {
        unitNumber: 5,
        title: 'Storage, Indexing & Query Optimization',
        description: 'File organization, B and B+ Trees, hashing techniques, and query evaluation plans.',
        topics: [
          'File Organizations & Record Formats',
          'B-Trees and B+ Trees Indexing',
          'Static and Dynamic Hashing',
          'Clustered vs Non-Clustered Indexes',
          'Query Evaluation and Cost Estimation',
        ],
      },
    ],
  },
  {
    name: 'Operating Systems',
    code: 'CS502',
    semester: 5,
    branch: 'CSE',
    credits: 4,
    description:
      'Core concepts of operating system design, process synchronization, CPU scheduling, memory virtualization, paging, and file systems.',
    units: [
      {
        unitNumber: 1,
        title: 'Process Management & CPU Scheduling',
        description: 'Process states, PCB, threads, and scheduling algorithms.',
        topics: ['Process States & PCB', 'CPU Scheduling Algorithms', 'Inter-process Communication'],
      },
      {
        unitNumber: 2,
        title: 'Process Synchronization & Deadlocks',
        description: 'Semaphores, monitors, classic synchronization problems, and Banker algorithm.',
        topics: ['Critical Section Problem', 'Semaphores & Mutex', 'Bankers Algorithm for Deadlock Avoidance'],
      },
      {
        unitNumber: 3,
        title: 'Memory Management & Virtual Memory',
        description: 'Paging, segmentation, page replacement algorithms, and thrashing.',
        topics: ['Paging & TLB', 'Page Replacement (FIFO, LRU, Optimal)', 'Thrashing & Working Set Model'],
      },
      {
        unitNumber: 4,
        title: 'Storage & File Systems',
        description: 'Disk scheduling algorithms, file allocation methods, and directory structures.',
        topics: ['Disk Scheduling (FCFS, SSTF, SCAN, C-SCAN)', 'File Allocation Methods', 'Directory Implementation'],
      },
      {
        unitNumber: 5,
        title: 'Protection & Security',
        description: 'Security threats, authentication, access control matrix, and cryptographic protection.',
        topics: ['Access Matrix', 'Authentication & Authorization', 'System Threats & Malware Protection'],
      },
    ],
  },
  {
    name: 'Computer Networks',
    code: 'CS503',
    semester: 5,
    branch: 'CSE',
    credits: 4,
    description:
      'Architecture and protocols of the Internet, OSI and TCP/IP reference models, routing algorithms, transport protocols, and network security.',
    units: [
      {
        unitNumber: 1,
        title: 'Physical & Data Link Layer',
        description: 'Transmission media, error detection/correction, and MAC protocols.',
        topics: ['OSI vs TCP/IP Models', 'CRC Error Detection & Hamming Code', 'CSMA/CD & Ethernet'],
      },
      {
        unitNumber: 2,
        title: 'Network Layer & Routing',
        description: 'IP addressing, subnetting, CIDR, distance vector, and link state routing.',
        topics: ['IPv4 Addressing & Subnetting', 'Distance Vector Routing', 'OSPF & Link State Routing'],
      },
      {
        unitNumber: 3,
        title: 'Transport Layer Protocols',
        description: 'TCP 3-way handshake, flow control, congestion control, and UDP.',
        topics: ['TCP vs UDP', 'TCP Flow Control & Sliding Window', 'TCP Congestion Control Algorithms'],
      },
      {
        unitNumber: 4,
        title: 'Application Layer',
        description: 'DNS, HTTP/HTTPS, FTP, SMTP, and DHCP protocols.',
        topics: ['DNS Resolution', 'HTTP/1.1 vs HTTP/2', 'Email Protocols (SMTP, POP3, IMAP)'],
      },
      {
        unitNumber: 5,
        title: 'Network Security',
        description: 'Cryptography, symmetric and asymmetric keys, digital signatures, and firewalls.',
        topics: ['RSA Algorithm', 'Symmetric vs Asymmetric Encryption', 'Firewalls & SSL/TLS'],
      },
    ],
  },
  {
    name: 'Data Structures & Algorithms',
    code: 'CS301',
    semester: 3,
    branch: 'CSE',
    credits: 4,
    description:
      'Fundamental data structures, asymptotic notation, sorting, searching, trees, graph algorithms, and dynamic programming.',
    units: [
      {
        unitNumber: 1,
        title: 'Arrays, Stacks & Queues',
        description: 'Asymptotic notation, stack applications, and queue variants.',
        topics: ['Big-O Notation', 'Infix to Postfix Conversion', 'Circular & Priority Queues'],
      },
      {
        unitNumber: 2,
        title: 'Linked Lists & Trees',
        description: 'Singly/doubly linked lists, binary trees, BST, and AVL tree balancing.',
        topics: ['Doubly Linked List Operations', 'Binary Search Tree Traversals', 'AVL Tree Rotations'],
      },
      {
        unitNumber: 3,
        title: 'Graphs & Searching Algorithms',
        description: 'Graph representations, BFS, DFS, and topological sort.',
        topics: ['BFS and DFS Traversals', 'Dijkstras Shortest Path Algorithm', 'Prims & Kruskals MST'],
      },
      {
        unitNumber: 4,
        title: 'Sorting & Hashing',
        description: 'Merge sort, quick sort, heap sort, and hash collision resolution.',
        topics: ['Quick Sort & Randomized Quick Sort', 'Heap Sort & Priority Queues', 'Hashing & Chaining'],
      },
      {
        unitNumber: 5,
        title: 'Algorithm Design Techniques',
        description: 'Greedy method, divide and conquer, dynamic programming, and backtracking.',
        topics: ['0/1 Knapsack Problem', 'Longest Common Subsequence (LCS)', 'N-Queens Problem'],
      },
    ],
  },
  {
    name: 'Software Engineering',
    code: 'CS504',
    semester: 5,
    branch: 'CSE',
    credits: 3,
    description:
      'Software development life cycle, agile methodologies, requirements engineering, software architecture, testing, and project management.',
    units: [
      {
        unitNumber: 1,
        title: 'Software Process & Agile Development',
        description: 'SDLC models, waterfall, spiral, agile manifesto, and scrum framework.',
        topics: ['Waterfall vs Spiral Model', 'Agile Principles & Scrum', 'DevOps Fundamentals'],
      },
      {
        unitNumber: 2,
        title: 'Requirements Engineering & Modeling',
        description: 'SRS document, use case diagrams, and sequence diagrams.',
        topics: ['Functional & Non-Functional Requirements', 'Use Case Modeling', 'Sequence & Activity Diagrams'],
      },
      {
        unitNumber: 3,
        title: 'Software Architecture & Design',
        description: 'Architectural styles, modularity, coupling, and cohesion.',
        topics: ['Cohesion & Coupling Metrics', 'Microservices vs Monolithic Architecture', 'Design Patterns'],
      },
      {
        unitNumber: 4,
        title: 'Software Testing & Quality Assurance',
        description: 'Black-box, white-box testing, cyclomatic complexity, and unit testing.',
        topics: ['Black Box vs White Box Testing', 'Cyclomatic Complexity & Basis Path Testing', 'Test-Driven Development (TDD)'],
      },
      {
        unitNumber: 5,
        title: 'Project Management & Maintenance',
        description: 'Effort estimation with COCOMO, risk management, and reverse engineering.',
        topics: ['COCOMO Estimation Model', 'Software Risk Management', 'Software Maintenance Types'],
      },
    ],
  },
];

const pyqsDBMSData = [
  {
    question: 'Explain 3NF and BCNF with suitable examples. Under what conditions is a relation in 3NF but not in BCNF?',
    unit: 3,
    topic: 'Normalization & Normal Forms',
    year: 2025,
    marks: 10,
    difficulty: 'Medium',
    frequency: 4,
    important: true,
    solution:
      '3NF requires that for every non-trivial FD X -> A: either X is a superkey, or A is a prime attribute (part of some candidate key). BCNF is stricter: X must be a superkey for EVERY non-trivial FD X -> A.\n\nA relation is in 3NF but NOT BCNF when X is not a superkey, but A is a prime attribute. For example: R(Student, Subject, Teacher), with FDs: {Student, Subject} -> Teacher and Teacher -> Subject. Candidate keys are {Student, Subject} and {Student, Teacher}. In Teacher -> Subject, Teacher is not a superkey, but Subject is prime, so it satisfies 3NF but violates BCNF.',
  },
  {
    question: 'Explain ACID properties of a database transaction with real-world banking examples.',
    unit: 4,
    topic: 'Transaction Management',
    year: 2024,
    marks: 10,
    difficulty: 'Easy',
    frequency: 5,
    important: true,
    solution:
      'ACID stands for:\n1. Atomicity: All or nothing execution. If transferring $100 from A to B fails after deducting from A, the entire transaction is rolled back.\n2. Consistency: Database remains in a valid state before and after the transaction (e.g. Total sum of A and B accounts remains constant).\n3. Isolation: Concurrent transactions do not interfere with one another (serializable execution).\n4. Durability: Once committed, updates persist even across system crashes or power failures.',
  },
  {
    question: 'What is an ER Diagram? Design and draw a complete ER diagram for a University Management System showing entities, attributes, primary keys, and cardinality ratios.',
    unit: 1,
    topic: 'ER Modeling',
    year: 2025,
    marks: 10,
    difficulty: 'Medium',
    frequency: 4,
    important: true,
    solution:
      'An Entity-Relationship (ER) diagram is a visual conceptual representation of data requirements. In a University System:\n- Entities: STUDENT (RollNo, Name, Email), INSTRUCTOR (EmpId, Name, Department), COURSE (CourseId, Title, Credits), DEPARTMENT (DeptId, DeptName).\n- Relationships: ENROLLS (Student to Course, M:N), TEACHES (Instructor to Course, 1:N), BELONGS_TO (Student/Instructor to Department, N:1).\n- Cardinality & Participation: Every student must belong to exactly one department (Total participation).',
  },
  {
    question: 'Differentiate between Two-Phase Locking (2PL), Strict 2PL, and Rigorous 2PL with concurrency graphs.',
    unit: 4,
    topic: 'Concurrency Control',
    year: 2023,
    marks: 7,
    difficulty: 'Medium',
    frequency: 3,
    important: true,
    solution:
      '1. Basic 2PL: Consists of Growing Phase (locks acquired, no locks released) and Shrinking Phase (locks released, no locks acquired). Ensures conflict serializability, but can suffer from cascading aborts.\n2. Strict 2PL: All exclusive (X) locks must be held until the transaction commits or aborts. Prevents cascading rollbacks.\n3. Rigorous 2PL: All locks (both Shared and Exclusive) are held until transaction completion. Schedules are strictly serializable.',
  },
  {
    question: 'Explain B+ Tree indexing structure. Why is B+ Tree preferred over B Tree and binary search trees in relational databases?',
    unit: 5,
    topic: 'Indexing & B+ Trees',
    year: 2024,
    marks: 10,
    difficulty: 'Hard',
    frequency: 3,
    important: true,
    solution:
      'A B+ Tree is an n-ary self-balancing search tree where:\n1. All data pointers/records reside only at leaf nodes.\n2. Non-leaf nodes store only search keys as routers/index.\n3. Leaf nodes are linked sequentially as a doubly linked list, enabling highly efficient range queries (e.g., SELECT * WHERE age BETWEEN 20 AND 30).\n4. Higher fanout means shallower tree height, minimizing expensive disk I/O operations compared to BSTs and standard B-Trees.',
  },
  {
    question: 'What is Lossless Join Decomposition and Dependency Preservation? Provide testing algorithms for both.',
    unit: 3,
    topic: 'Relational Decomposition',
    year: 2023,
    marks: 10,
    difficulty: 'Hard',
    frequency: 3,
    important: true,
    solution:
      'Lossless Join Decomposition ensures that natural join of decomposed relations R1 and R2 recovers the exact original relation R without spurious tuples: R1 ∩ R2 -> R1 or R1 ∩ R2 -> R2 (the common attributes must form a superkey for at least one relation).\n\nDependency Preservation requires that the union of functional dependencies in decomposed relations (F1 ∪ F2)+ covers all original dependencies F+ without needing costly joins across relations.',
  },
  {
    question: 'Explain Conflict Serializability and View Serializability. How does a precedence (wait-for) graph test for conflict serializability?',
    unit: 4,
    topic: 'Serializability',
    year: 2025,
    marks: 10,
    difficulty: 'Hard',
    frequency: 4,
    important: true,
    solution:
      'Two operations conflict if they belong to different transactions, access the same data item, and at least one is a WRITE.\nA schedule is conflict serializable if it can be transformed into a serial schedule by swapping non-conflicting operations.\nPrecedence Graph Test: Create nodes for each transaction Ti. Draw a directed edge Ti -> Tj if Ti executes a conflicting operation before Tj. If the graph contains no cycles, the schedule is conflict serializable.',
  },
  {
    question: 'Write SQL queries using nested subqueries, GROUP BY, HAVING, and correlated subqueries on an Employee database.',
    unit: 2,
    topic: 'SQL Queries',
    year: 2024,
    marks: 10,
    difficulty: 'Medium',
    frequency: 4,
    important: true,
    solution:
      '1. Highest salary in each department:\nSELECT DeptId, MAX(Salary) FROM Employee GROUP BY DeptId HAVING COUNT(*) > 2;\n\n2. Employees earning more than average department salary (Correlated Subquery):\nSELECT E.Name, E.Salary, E.DeptId FROM Employee E WHERE E.Salary > (SELECT AVG(Salary) FROM Employee WHERE DeptId = E.DeptId);',
  },
  {
    question: 'Differentiate between Clustered and Non-Clustered indexing with diagrams and performance trade-offs.',
    unit: 5,
    topic: 'Storage & Indexing',
    year: 2025,
    marks: 5,
    difficulty: 'Easy',
    frequency: 3,
    important: false,
    solution:
      '1. Clustered Index: Determines the physical storage order of data in the table. There can only be ONE clustered index per table (usually Primary Key). Highly efficient for range queries.\n2. Non-Clustered Index: Separate structure from data rows that holds key values and pointers to data rows (RID or clustered key). A table can have multiple non-clustered indexes.',
  },
  {
    question: 'Explain Deadlock handling techniques in DBMS: Prevention (Wait-Die, Wound-Wait), Detection, and Recovery.',
    unit: 4,
    topic: 'Deadlock Handling',
    year: 2022,
    marks: 7,
    difficulty: 'Medium',
    frequency: 2,
    important: false,
    solution:
      'Deadlock prevention uses timestamps TS(T):\n- Wait-Die (Non-preemptive): If older Ti requests item held by younger Tj, Ti waits. If younger Ti requests item held by older Tj, Ti dies and rolls back.\n- Wound-Wait (Preemptive): If older Ti requests item held by younger Tj, Ti wounds Tj and forces Tj to abort. If younger Ti requests item held by older Tj, Ti waits.\nRecovery involves selecting a victim transaction, rollback, and starvation prevention.',
  },
  {
    question: 'Explain Relational Algebra fundamental operations: Selection, Projection, Cartesian Product, Union, and Set Difference.',
    unit: 1,
    topic: 'Relational Algebra',
    year: 2023,
    marks: 10,
    difficulty: 'Easy',
    frequency: 3,
    important: true,
    solution:
      'Fundamental operations:\n1. Selection (σ): Filters rows based on condition (e.g., σ_{age > 20}(Student)).\n2. Projection (π): Extracts specified columns and removes duplicates (e.g., π_{name, roll}(Student)).\n3. Cartesian Product (✕): Combines every tuple of R with every tuple of S.\n4. Union (∪): Combines tuples from two union-compatible relations.\n5. Set Difference (-): Tuples in relation R but not in relation S.',
  },
  {
    question: 'What are Triggers and Views in SQL? What are the advantages of updatable views and materialized views?',
    unit: 2,
    topic: 'Views and Triggers',
    year: 2022,
    marks: 7,
    difficulty: 'Medium',
    frequency: 2,
    important: false,
    solution:
      '1. Views: Virtual tables defined by an underlying query. Provide data security and simplify complex queries. Materialized views physically store query results and refresh periodically for high-speed reporting.\n2. Triggers: Stored procedures automatically invoked in response to specific DML events (BEFORE/AFTER INSERT, UPDATE, DELETE) to enforce business rules and audit logging.',
  },
  {
    question: 'Explain Multi-Valued Dependencies (MVD) and Fourth Normal Form (4NF) with a counterexample.',
    unit: 3,
    topic: '4NF & MVD',
    year: 2024,
    marks: 7,
    difficulty: 'Hard',
    frequency: 2,
    important: false,
    solution:
      'A multi-valued dependency X ->-> Y occurs when given X, the set of values for Y depends only on X and is independent of other attributes Z. A relation is in 4NF if it is in BCNF and for every non-trivial MVD X ->-> Y, X is a superkey.\nExample: R(Professor, Course, Hobby). A professor teaches multiple courses and has multiple independent hobbies. This creates Cartesian redundancy and violates 4NF unless decomposed into R1(Professor, Course) and R2(Professor, Hobby).',
  },
  {
    question: 'Explain Query Optimization. Describe the steps involved in transforming a SQL query into an optimized physical query execution plan.',
    unit: 5,
    topic: 'Query Optimization',
    year: 2023,
    marks: 10,
    difficulty: 'Hard',
    frequency: 2,
    important: false,
    solution:
      'Steps:\n1. Parsing and Translation: SQL is parsed, verified against schema, and converted into relational algebra tree.\n2. Optimization: Heuristic rules are applied (push selections and projections down the tree, reorder joins to minimize intermediate relations).\n3. Cost Estimation: Catalog statistics (cardinality, index availability) calculate estimated I/O and CPU cost.\n4. Execution Plan: Optimal physical plan is chosen for execution engine.',
  },
  {
    question: 'Explain Static Hashing vs Dynamic Hashing (Extendible Hashing). How does extendible hashing handle bucket overflow without rehashing all records?',
    unit: 5,
    topic: 'Hashing Techniques',
    year: 2025,
    marks: 7,
    difficulty: 'Medium',
    frequency: 3,
    important: true,
    solution:
      'Static hashing uses a fixed number of buckets, leading to severe bucket overflow chains as data grows. Extendible hashing is a dynamic hashing technique using a directory of pointers and global/local depths. When a bucket overflows: if local depth < global depth, only the overflowing bucket splits into two, and pointers in the directory are updated; if local depth = global depth, the directory size doubles, avoiding complete rehashing.',
  },
];

const sampleResourcesData = [
  {
    title: 'Complete DBMS Unit 1–5 Hand-Written Revision Notes',
    description: 'Concise, high-yield revision notes covering relational model, SQL queries, normalization shortcuts, and transaction schedules.',
    type: 'Notes',
    unit: 1,
    url: 'https://example.com/resources/dbms-complete-notes.pdf',
  },
  {
    title: 'University Official Syllabus & Scheme 2025',
    description: 'Detailed unit-wise syllabus, recommended textbooks, and evaluation rubrics for Database Management Systems.',
    type: 'Syllabus',
    unit: 1,
    url: 'https://example.com/resources/dbms-syllabus-2025.pdf',
  },
  {
    title: 'Normalization Masterclass & Solved Numerical Problems',
    description: 'Step-by-step solved examples for finding candidate keys, attribute closures, 3NF, and BCNF decomposition.',
    type: 'Reference',
    unit: 3,
    url: 'https://example.com/resources/normalization-practice-guide.pdf',
  },
  {
    title: 'Transaction & Concurrency Control Solved PYQ Compilation (2020–2025)',
    description: 'Full compilation of all serializability and 2PL exam questions with detailed explanations.',
    type: 'PYQ',
    unit: 4,
    url: 'https://example.com/resources/dbms-pyq-unit4-compilation.pdf',
  },
  {
    title: 'Interactive B+ Tree Simulation & Video Walkthrough',
    description: 'Visualizer guide demonstrating node splitting, leaf chaining, and search operations in B+ Trees.',
    type: 'Video',
    unit: 5,
    url: 'https://www.youtube.com/watch?v=aZjYr87r1b8',
  },
  {
    title: 'SQL Practice Sheet with Solutions (DDL, Joins, Aggregation)',
    description: '50 essential SQL interview and university exam practice questions with schema and solutions.',
    type: 'Practice',
    unit: 2,
    url: 'https://example.com/resources/sql-practice-sheet.pdf',
  },
];

module.exports = {
  semestersData,
  subjectsData,
  pyqsDBMSData,
  sampleResourcesData,
};
